### ISSUE TITLE
Add tests to make sure that we able to backup and restore multiple configs

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-backup#107]
We've added a feature that allows backing up multiple configurations: https://github.com/manticoresoftware/manticoresearch-backup/pull/106

Now, we need to ensure it's working correctly by testing:
1. Backing up multiple configurations is successful.
2. Restoring multiple configurations is successful.

To back up multiple configurations, execute the backup tool with flags `--config=config1.conf --config=config2.conf`, ensuring both are included in the backup. The first configuration will be used to connect to the daemon.

When restoring, verify that both configurations are properly restored.

**Comment by PavelShilin89** [comment]
Done in https://github.com/manticoresoftware/manticoresearch-backup/pull/109
