### ISSUE TITLE
https listener prevents from connecting to Manticore Search

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/manticoresearch-backup#59]
If you have this in the config:  
  
```  
    listen = 9312  
    listen = 127.0.0.1:9306:mysql  
    listen = 127.0.0.1:9308:http  
    listen = 127.0.0.1:9343:https  
```  
  
`manticore-backup` will fail like this:  
  
```  
➜  ~ manticore-backup --backup-dir=/tmp/  
Copyright (c) 2023, Manticore Software LTD (https://manticoresearch.com)  
  
Manticore config file: /opt/homebrew/Cellar/manticoresearch/6.0.4-2023031400-aba1e25ec/etc/manticoresearch/manticore.conf  
Tables to backup: all tables  
Backup dir: /tmp/  
  
Manticore config  
  endpoint =  127.0.0.1:9343  
2023-03-27 06:07:38 [Error] Failed to connect to the manticoresearch daemon. Is it running?  
```  
  
The task is to parse the listeners better and put proper priorities. I suggest `manticore-backup`:  
* first attempts to connect to `127.0.0.1:*:http`  
* then `<port>:http` (w/o ip specified)  
* then `<port>` (w/o any listen mode specified)  
* then `x.x.x.x:*:http` (i.e. not `127.0.0.1`)  
* then `x.x.x.x:*` (not `127.0.0.1`, w/o listen mode)  
* then `127.0.0.1:*:https`  
* then `x.x.x.x:*:https`  
  
Another task is to figure out the most optimal way to connect via https:  
* is it ok to still connect to an https listener on 127.0.0.1 when the certificate is misconfigured in Manticore Search?  
* what about not 127.0.0.1?

**Comment by donhardman** [comment]
This should be fixed in this pull request – https://github.com/manticoresoftware/manticoresearch-backup/pull/65

**Comment by sanikolaev** [comment]
Looks ok now. As for the https, it fails like this now:

```
root@perf ~ # manticore-backup --backup-dir=/tmp/
Copyright (c) 2023, Manticore Software LTD (https://manticoresearch.com)

Manticore config file: /etc/manticoresearch/manticore.conf
Tables to backup: all tables
Backup dir: /tmp/

Manticore config
  endpoint =  https://127.0.0.1:9343
2023-03-31 11:53:36 [Error] Failed to connect to the manticoresearch daemon. Is it running?
root@perf ~ #
```

Would it be possible to return another error in case the connection can be established, but the backup can't be made due to security reasons?

**Comment by githubmanticore** [comment]
➤ Sergey Nikolaev commented:
 

 
Looks ok now, just a little error message update in this PR https://github.com/manticoresoftware/manticoresearch-backup/pull/66

**Comment by githubmanticore** [comment]
➤ Don Hardman commented:
 

 
I have merged it. I guess I can close the issue.
