### ISSUE TITLE
Wrong ownership after installation in Debian/Ubuntu

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/manticoresearch-backup#82]
When you install manticore-backup in Debian/Ubuntu under root the ownership looks like this:
```
root@78c483766894:/backup# ls -la usr/share/manticore/modules/manticore-backup/
total 104
drwxr-xr-x 4 1001 123  4096 Aug  4 08:41 .
drwxr-xr-x 3 1001 123  4096 Aug  4 08:41 ..
-rw-r--r-- 1 1001 123     6 Aug  4 08:41 APP_VERSION
-rw-r--r-- 1 1001 123   760 Aug  4 08:41 composer.json
-rw-r--r-- 1 1001 123 79259 Aug  4 08:41 composer.lock
drwxr-xr-x 4 1001 123  4096 Aug  4 08:41 src
drwxr-xr-x 4 1001 123  4096 Aug  4 08:41 vendor
```

The task is to figure out where `1001:123` comes from and remove it unless it's really required. 

E.g. here's what it looks like for MCL:

```
root@78c483766894:/mcl# ls -la usr/share/manticore/modules/
total 8252
drwxr-xr-x 2 root root    4096 Aug 22 09:57 .
drwxr-xr-x 3 root root    4096 Aug 22 09:57 ..
-rw-r--r-- 1 root root 7146544 Aug 22 09:57 lib_manticore_columnar.so
-rw-r--r-- 1 root root 1292504 Aug 22 09:57 lib_manticore_secondary.so
```

**Comment by donhardman** [comment]
Fixed for Backup & Buddy:

https://github.com/manticoresoftware/manticoresearch-buddy/pull/174
https://github.com/manticoresoftware/manticoresearch-backup/pull/91

![Image](https://github.com/manticoresoftware/manticoresearch-backup/assets/59067742/75320155-0bf4-4756-838d-559080732630)
